name: Daily Routines (DISABLED)

on:
  # Disabling all triggers
  # schedule:
  #   - cron: "0 7 * * 3,0"
  # workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is disabled."
